/*
 * This source file was generated by the Gradle 'init' task
 */
package devices.network;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import devices.adapter.in.web.NetworkController;
import devices.application.DevicesNetworkQueryUseCase;
import devices.domain.DevicesNetwork;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import devices.domain.Device;
import devices.domain.DeviceType;

class DevicesNetworkTest {


    @Test
    void should_Not_Accept_Duplicate_Devices() {
        DevicesNetwork network = new DevicesNetwork();
        String duplicateMacAddress = "00:01";

        Device switchDevice = new Device(duplicateMacAddress, DeviceType.SWITCH, null);

        Device gateway = new Device(duplicateMacAddress, DeviceType.GATEWAY, null);

        network.registerDevice(switchDevice);

        assertThatThrownBy(() -> network.registerDevice(gateway))
                .isInstanceOf(DevicesNetwork.DuplicateDeviceException.class);
        assertThatIterable(network.getRegisteredDevices())
                .containsExactly(switchDevice);
    }

    @Test
    void can_Register_Device_To_Network() {
        DevicesNetwork network= new DevicesNetwork();
        assertNull(network.getRegisteredDevice("00:01"));

        Device device = aSwitch("00:01", null);
        network.registerDevice(device);

        assertEquals(device, network.getRegisteredDevice("00:01"));
    }

    @Test
    void can_List_Devices_OnNetwork_Sorted_By_Type() {
        DevicesNetwork network = new DevicesNetwork();
        Device switchOne = aSwitch("00:01", null);
        Device gateway = aGateway("00:02", null);
        Device switchTwo = aSwitch("00:03", null);
        Device accessPoint = anAccesspoint("00:04", null);

        registerDevices(network, switchOne, gateway, switchTwo, accessPoint);

        assertThatIterable(network.getRegisteredDevices())
                .containsExactly(gateway, switchOne, switchTwo,
                        accessPoint);
    }

    @Test
    void can_Add_Connected_Devices_In_Network() {
        DevicesNetwork network = new DevicesNetwork();
        Device switchOne = aSwitch("00:01", null);
        Device switchthree = aSwitch("00:09", null);

        Device gateway = aGateway("00:02", "00:01");
        Device switchTwo = aSwitch("00:03", "00:01");
        Device accessPoint = anAccesspoint("00:04", "00:01");

        registerDevices(network, switchOne,switchthree, gateway, switchTwo, accessPoint);

        assertThatIterable(switchOne.getConnectedDevices())
                .contains(gateway, switchTwo, accessPoint);

        Device gatewayTwo = aGateway("00:05", "00:03");

        registerDevices(network, gatewayTwo);

        assertThatIterable(switchTwo.getConnectedDevices())
                .containsExactly(gatewayTwo);
    }

    @Test
    void can_Add_Connected_Devices_Out_Of_Order() {
         DevicesNetwork devicesNetwork = new DevicesNetwork();
        Device switchOne = aSwitch("00:01", null);
        Device gateway = aGateway("00:02", "00:01");
        Device switchTwo = aSwitch("00:03", "00:01");
        Device accessPoint = anAccesspoint("00:04", "00:01");

        registerDevices(devicesNetwork, gateway, switchTwo, accessPoint, switchOne);

        assertThatIterable(switchOne.getConnectedDevices())
                .contains(gateway, switchTwo, accessPoint);
    }

    @Test
    void can_Not_Establish_Cyclic_Connections() {
        DevicesNetwork network = new DevicesNetwork();
        network.registerDevice(new Device("00:01", DeviceType.GATEWAY, null));
        network.registerDevice(new Device("00:02", DeviceType.SWITCH, null));
        network.registerDevice(new Device("00:03", DeviceType.ACCESS_POINT, "00:04"));

        assertThatThrownBy(() -> network.registerDevice(new Device("00:04", DeviceType.GATEWAY, "00:03")))
                .isInstanceOf(DevicesNetwork.CyclicUplinkReferenceException.class);

        assertThat(network.getRegisteredDevice("00:04")).isNull();
        
        assertThatThrownBy(() -> network.registerDevice(aGateway("00", "00")))
                .isInstanceOf(DevicesNetwork.CyclicUplinkReferenceException.class);
    }

    @Test
    void should_Be_Empty_Before_Device_Registrations(){

        DevicesNetwork network = new DevicesNetwork();
        assertThat(network.getRegisteredDevices()).isEmpty();
        assertThat(network.getTopology().getConnectedDevices()).isEmpty();
    }

    @Test
    void shouldRegisterMultipleDevicesWithoutUplinkConnection(){
        Device switchOne = aSwitch("00:01", null);
        Device gateway = aGateway("00:02", null);

        DevicesNetwork network = new DevicesNetwork();
        network.registerDevice(switchOne);
        network.registerDevice(gateway);

        assertThatIterable(network.getTopology().getConnectedDevices())
                .contains(gateway, switchOne);
    }

    private void registerDevices(DevicesNetwork network,Device... devices) {
        for (Device device : devices) {
            network.registerDevice(device);
        }
    }

    private Device aGateway(String macAddress, String uplinkAddress) {
        return new Device(macAddress, DeviceType.GATEWAY, uplinkAddress);
    }

    private Device aSwitch(String macAddress, String uplinkAddress) {
        return new Device(macAddress, DeviceType.SWITCH, uplinkAddress);
    }

    private Device anAccesspoint(String macAddress, String uplinkAddress) {
        return new Device(macAddress, DeviceType.ACCESS_POINT, uplinkAddress);
    }
}
