/*
 * This source file was generated by the Gradle 'init' task
 */
package devices.network;

import devices.domain.Device;
import devices.domain.DeviceType;
import devices.domain.DevicesNetwork;
import devices.domain.InvalidMacAddressException;
import org.junit.jupiter.api.Test;

import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.*;

class DevicesNetworkTest {

    @Test
     void shouldNotAcceptInvalidMacAddress(){
        assertThrows(
                InvalidMacAddressException.class,
                () -> new Device("invalidAddress", DeviceType.GATEWAY, null)
        );

        assertThrows(
                InvalidMacAddressException.class,
                () -> new Device("", DeviceType.GATEWAY, null)
        );
        assertThrows(
                InvalidMacAddressException.class,
                () -> new Device("", DeviceType.GATEWAY, null)
        );
    }


    @Test
    void should_Not_Accept_Duplicate_Devices() {
        DevicesNetwork network = new DevicesNetwork();
        String duplicateMacAddress = "01";

        Device switchDevice = aSwitch(duplicateMacAddress,null);

        Device gateway = aGateway(duplicateMacAddress,null);

        network.registerDevice(switchDevice);

        assertThatThrownBy(() -> network.registerDevice(gateway))
                .isInstanceOf(DevicesNetwork.DuplicateDeviceException.class);
        assertThatIterable(network.getRegisteredDevices())
                .containsExactly(switchDevice);
    }

    @Test
    void can_Register_Device_To_Network() {
        DevicesNetwork network= new DevicesNetwork();
        assertNull(network.getRegisteredDevice(givenMacAddress("01")));

        Device device = aSwitch("01", null);
        network.registerDevice(device);

        assertEquals(device, network.getRegisteredDevice(givenMacAddress("01")));
    }

    @Test
    void can_List_Devices_OnNetwork_Sorted_By_Type() {
        DevicesNetwork network = new DevicesNetwork();
        Device switchOne = aSwitch("01", null);
        Device gateway = aGateway("02", null);
        Device switchTwo = aSwitch("03", null);
        Device accessPoint = anAccesspoint("04", null);

        registerDevices(network, switchOne, gateway, switchTwo, accessPoint);

        assertThatIterable(network.getRegisteredDevices())
                .containsExactly(gateway, switchOne, switchTwo,
                        accessPoint);
    }

    @Test
    void can_Add_Connected_Devices_In_Network() {
        DevicesNetwork network = new DevicesNetwork();
        Device switchOne = aSwitch("01", null);
        Device switchthree = aSwitch("09", null);

        Device gateway = aGateway("02", "01");
        Device switchTwo = aSwitch("03", "01");
        Device accessPoint = anAccesspoint("04", "01");

        registerDevices(network, switchOne,switchthree, gateway, switchTwo, accessPoint);

        assertThatIterable(switchOne.getConnectedDevices())
                .contains(gateway, switchTwo, accessPoint);

        Device gatewayTwo = aGateway("05", "03");

        registerDevices(network, gatewayTwo);

        assertThatIterable(switchTwo.getConnectedDevices())
                .containsExactly(gatewayTwo);
    }

    @Test
    void can_Add_Connected_Devices_Out_Of_Order() {
        DevicesNetwork devicesNetwork = new DevicesNetwork();

        Device switchOne = aSwitch("A1", null);
        Device gateway = aGateway("A2", "A1");
        Device switchTwo = aSwitch("A3", "A1");
        Device accessPoint = anAccesspoint("A4", "A1");

        registerDevices(devicesNetwork, gateway, switchTwo, accessPoint, switchOne);

        assertThatIterable(switchOne.getConnectedDevices())
                .contains(gateway, switchTwo, accessPoint);
    }

    @Test
    void can_Not_Establish_Cyclic_Connections() {
        DevicesNetwork network = new DevicesNetwork();
        network.registerDevice(aGateway("01",null));
        network.registerDevice(aSwitch("02",null));
        network.registerDevice(anAccesspoint("03","04"));

        assertThatThrownBy(() -> network.registerDevice(aGateway("04","03")))
                .isInstanceOf(DevicesNetwork.CyclicUplinkReferenceException.class);

        assertThat(network.getRegisteredDevice("04")).isNull();
        
        assertThatThrownBy(() -> network.registerDevice(aGateway("00", "00")))
                .isInstanceOf(DevicesNetwork.CyclicUplinkReferenceException.class);
    }

    @Test
    void should_Be_Empty_Before_Device_Registrations(){

        DevicesNetwork network = new DevicesNetwork();
        assertThat(network.getRegisteredDevices()).isEmpty();
        assertThat(network.getTopology().getConnectedDevices()).isEmpty();
    }

    @Test
    void shouldRegisterMultipleDevicesWithoutUplinkConnection(){
        Device switchOne = aSwitch("D1", null);
        Device gateway = aGateway("D2", null);

        DevicesNetwork network = new DevicesNetwork();
        network.registerDevice(switchOne);
        network.registerDevice(gateway);

        assertThatIterable(network.getTopology().getConnectedDevices())
                .contains(gateway, switchOne);
    }

    private void registerDevices(DevicesNetwork network,Device... devices) {
        for (Device device : devices) {
            network.registerDevice(device);
        }
    }

    private Device aGateway(String macAddress, String uplinkAddress) {
        return new Device(givenMacAddress(macAddress), DeviceType.GATEWAY, givenMacAddress(uplinkAddress));
    }

    private Device aSwitch(String macAddress, String uplinkAddress) {
        return new Device(givenMacAddress(macAddress), DeviceType.SWITCH, givenMacAddress(uplinkAddress));
    }

    private Device anAccesspoint(String macAddress, String uplinkAddress) {
        return new Device(givenMacAddress(macAddress), DeviceType.ACCESS_POINT, givenMacAddress(uplinkAddress));
    }

    private String givenMacAddress(String suffix){

        return Optional.ofNullable(suffix).map((s) -> "CB:0B:B6:9B:34:" + s).orElse(null);
    }
}
