/*
 * This source file was generated by the Gradle 'init' task
 */
package devices;

import devices.adapter.out.InMemoryDevicesNetworkRepository;
import devices.application.DevicesNetworkQueryUseCase;
import devices.application.RegisterDeviceUseCase;
import devices.port.out.DevicesNetworkRepository;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
